apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-operator
  namespace: {{ .Values.operator.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kong-operator
  template:
    metadata:
      labels:
        name: kong-operator
    spec:
      serviceAccountName: kong-operator
      containers:
        - name: kong-operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.operator.namespace }}
          resources:
          {{- toYaml .Values.operator.resources | nindent 11 }}
