{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "kong.name" . }}
  namespace: {{ include "kong.namespace" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: {{ .Values.istio.gateway.portNumber }}
      name: "{{ .Values.istio.gateway.portName }}"
      protocol: "{{ .Values.istio.gateway.protocol }}"
    hosts:
    - "{{ .Values.istio.gateway.ingressHost }}"
{{- end }}
