{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "kong-operator.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
  name: {{ include "kong.name" . }}
  namespace: {{ include "kong.namespace" . }}
spec:
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: {{ .Values.serviceMonitor.port }}
  selector:
    matchLabels:
   {{- toYaml .Values.kong.admin.labels | nindent 7 }}
{{- end }}
